<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CouponService.Application\CouponService.Application.csproj" />
    <ProjectReference Include="..\CouponService.Engine\CouponService.Engine.csproj" />
    <ProjectReference Include="..\CouponService.Infrastructure\CouponService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
